<?php
/**
 * Add styles generated by brunch
*/
function bfamfaphd_assets() {
	wp_enqueue_style( 'bfamfaphd-style', get_template_directory_uri() . '/css/app.css');
	wp_enqueue_script( 'bfamfaphd-vendor-script', get_template_directory_uri() . '/js/vendor.js');
	wp_enqueue_script( 'bfamfaphd-script', get_template_directory_uri() . '/js/app.js');
}


add_action( 'wp_enqueue_scripts', 'bfamfaphd_assets' );

// Hide Admin Bar
add_filter('show_admin_bar', '__return_false');

// Create the_slug()
function the_slug() {
	    echo get_the_slug();
}
function get_the_slug() {
	    $post_data = get_post($post->ID, ARRAY_A);
	    return $post_data['post_name'];
}
add_theme_support('post-thumbnails');
require 'post_type_project.php';
require 'projects_gallery.php';
require 'projects_grid.php';
